included:
    - BetterSleep

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - R.generated.swift
  
disabled_rules:
 - trailing_whitespace
 - weak_delegate
 - identifier_name
 - colon
 - computed_accessors_order
 - statement_position
 - class_delegate_protocol
 - cyclomatic_complexity
 - redundant_string_enum_value
 - notification_center_detachment
 
line_length: 300 # warning - default: 300

closure_body_length: # Closure bodies should not span too many lines.
  - 100 # warning - default: 100
  - 300 # error - default: 300

enum_case_associated_values_count: # Number of associated values in an enum case should be low
  - 7 # warning - default: 7
  - 8 # error - default: 8

file_length: # Files should not span too many lines.
  - 500 # warning - default: 400
  - 1000 # error - default: 1000

function_body_length: # Functions bodies should not span too many lines.
  - 55 # warning - default: 40
  - 100 # error - default: 100

function_parameter_count: # Number of function parameters should be low.
  - 7 # warning - default: 7
  - 10 # error - default: 10


large_tuple: # Tuples shouldn't have too many members. Create a custom type instead.
  - 2 # warning - default: 2
  - 3 # error - default: 3

line_length: # Lines should not span too many characters.
  warning: 300 # default: 300
  error: 700 # default: 400
  ignores_comments: true # default: false
  ignores_urls: true # default: false
  ignores_function_declarations: false # default: false
  ignores_interpolated_strings: true # default: false

type_body_length: # Type bodies should not span too many lines.
  - 300 # warning - default: 300
  - 800 # error - default: 800


reporter: "xcode"
