# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'BetterSleep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterSleep
 
# Pod for Reactive Programming
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  
  # Pod for IQ Keyboard Manager Swift
  pod 'IQKeyboardManagerSwift'
 
# Pod for loading
  pod 'MBProgressHUD'
  
# Pod for UI
  pod 'FittedSheets'

# Pod for code beautification
  pod 'SwiftLint'

 # Pod for images
  pod 'Kingfisher'
  
  # Pod for popups
  pod 'PopupDialog'
  
  # Pod for Networking
   pod 'Alamofire'
   
   # Pod for images
   pod 'HGCircularSlider'
   
   # Pod for Json
   pod 'SwiftyJSON'
   
  target 'BetterSleepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterSleepUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end
